# all
[tasks.build-all]
dependencies = ["build","build-frontend","copy-frontend"]
script = ''

# frontend
[tasks.build-frontend]
cwd = "../frontend"
command = "npm"
args = ["run", "build"]

[tasks.copy-frontend]
script = '''
rm -rf ./static
mkdir -p ./static
cp -r ../frontend/.svelte-kit/output/client/* ./static
cp -r ../frontend/.svelte-kit/output/prerendered/pages/* ./static
'''


# backend
[tasks.sbom]
install_crate = "cargo-cyclonedx"
command = "cargo"
args = ["cyclonedx"]

[tasks.format]
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build","--release"]
dependencies = ["clean"]

[tasks.sqlx-prepare]
install_crate = "sqlx-cli"
env = { "DATABASE_URL" =  { script = ["echo -n sqlite:$(pwd)/db/sqlite/warehouse.sqlite"]} }
command = "cargo"
args = ["sqlx","prepare"]


[tasks.run]
dependencies = ["build-frontend","copy-frontend"]
command = "cargo"
args = ["run"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.build-flow]
dependencies = [
    "format",
    "build",
    "test"
]